//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_study_plan_generator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class custom_study_plan_generatorEntities : DbContext
    {
        public custom_study_plan_generatorEntities()
            : base("name=custom_study_plan_generatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentExemption> StudentExemptions { get; set; }
        public virtual DbSet<StudentPlan> StudentPlans { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitPrerequisite> UnitPrerequisites { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<DefaultPlan> DefaultPlans { get; set; }
        public virtual DbSet<StudentPlanUnit> StudentPlanUnits { get; set; }
    }
}
