//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_study_plan_generator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentExemptions = new HashSet<StudentExemption>();
            this.StudentPlans = new HashSet<StudentPlan>();
        }
    
        public int student_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    
        public virtual ICollection<StudentExemption> StudentExemptions { get; set; }
        public virtual ICollection<StudentPlan> StudentPlans { get; set; }
    }
}
