//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_study_plan_generator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExemption
    {
        public int student_id { get; set; }
        public string unit_code { get; set; }
        public bool exempt { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
