//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_study_plan_generator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPlan
    {
        public StudentPlan()
        {
            this.StudentPlanUnits = new HashSet<StudentPlanUnit>();
        }
    
        public int plan_id { get; set; }
        public int student_id { get; set; }
        public string course_code { get; set; }
        public Nullable<int> start_semester { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentPlanUnit> StudentPlanUnits { get; set; }
    }
}
