//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_study_plan_generator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.StudentExemptions = new HashSet<StudentExemption>();
            this.UnitPrerequisites = new HashSet<UnitPrerequisite>();
            this.UnitPrerequisites1 = new HashSet<UnitPrerequisite>();
            this.DefaultPlans = new HashSet<DefaultPlan>();
            this.StudentPlanUnits = new HashSet<StudentPlanUnit>();
        }
    
        public string unit_code { get; set; }
        public string name { get; set; }
        public string type_code { get; set; }
        public bool semester1 { get; set; }
        public bool semester2 { get; set; }
        public Nullable<int> preferred_year { get; set; }
    
        public virtual ICollection<StudentExemption> StudentExemptions { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual ICollection<UnitPrerequisite> UnitPrerequisites { get; set; }
        public virtual ICollection<UnitPrerequisite> UnitPrerequisites1 { get; set; }
        public virtual ICollection<DefaultPlan> DefaultPlans { get; set; }
        public virtual ICollection<StudentPlanUnit> StudentPlanUnits { get; set; }
    }
}
